// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var fpsCounter, fpsCounterTime, gameLoop, lastFrameTime, projectGaia, totalTime;

  projectGaia = new ProjectGaia;

  totalTime = 0;

  lastFrameTime = null;

  fpsCounter = 0;

  fpsCounterTime = 0;

  gameLoop = function(timestamp) {
    var elapsedTime, gameTime;
    if (lastFrameTime == null) {
      lastFrameTime = timestamp;
    }
    elapsedTime = (timestamp - lastFrameTime) / 1000;
    lastFrameTime = timestamp;
    elapsedTime = Math.min(1, elapsedTime);
    fpsCounter++;
    fpsCounterTime += elapsedTime;
    if (fpsCounterTime > 1) {
      console.log("Running at " + fpsCounter + " FPS");
      fpsCounter = 0;
      fpsCounterTime -= 1;
    }
    totalTime += elapsedTime;
    gameTime = {
      elapsedGameTime: elapsedTime,
      totalGameTime: totalTime
    };
    projectGaia.update(gameTime);
    projectGaia.draw(gameTime);
    return requestAnimationFrame(gameLoop);
  };

  requestAnimationFrame(gameLoop);

}).call(this);

//# sourceMappingURL=main.js.map
