// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ProjectGaia.Materials.BlocksInformation = (function(superClass) {
    extend(BlocksInformation, superClass);

    BlocksInformation.load = function(loadingManager) {
      return new THREE.FileLoader(loadingManager).load('classes/materials/blocksinformationfragmentshader.glsl', (function(_this) {
        return function(fragmentShader) {
          _this.fragmentShader = fragmentShader;
        };
      })(this));
    };

    function BlocksInformation(options) {
      var parameters;
      parameters = {
        blending: THREE.NoBlending,
        uniforms: _.extend({
          blocksInformation: {
            value: options.blocksInformationTexture.texture
          },
          blocksInformationSize: {
            value: new THREE.Vector2(options.blocksInformationTexture.texture.image.width, options.blocksInformationTexture.texture.image.height)
          },
          materialData: {
            value: options.materialsDataTexture
          },
          worldSize: {
            value: options.worldSizeVector
          },
          blockTypesCount: {
            value: _.keys(ProjectGaia.BlockTypes).length
          }
        }, ProjectGaia.Materials.getTimeUniforms()),
        vertexShader: ProjectGaia.ComputedTexture.vertexShader,
        fragmentShader: this.constructor.fragmentShader
      };
      BlocksInformation.__super__.constructor.call(this, parameters);
      this.options = options;
    }

    BlocksInformation.prototype.update = function(gameTime) {
      ProjectGaia.Materials.updateTimeUniforms(this.uniforms, gameTime);
      this.uniforms.blocksInformation.value = this.options.blocksInformationTexture.texture;
      return this.needsUpdate = true;
    };

    return BlocksInformation;

  })(THREE.RawShaderMaterial);

}).call(this);

//# sourceMappingURL=blocksinformation.js.map
