// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  ProjectGaia.Materials = (function() {
    function Materials() {}

    Materials.getTimeUniforms = function() {
      return {
        elapsedGameTime: {
          value: 0
        },
        totalGameTime: {
          value: 0
        }
      };
    };

    Materials.getRandomUniforms = function() {
      return {
        randomSeed: {
          value: Math.random()
        }
      };
    };

    Materials.updateTimeUniforms = function(uniforms, gameTime) {
      uniforms.elapsedGameTime.value = gameTime.elapsedGameTime;
      return uniforms.totalGameTime.value = gameTime.totalGameTime;
    };

    Materials.updateRandomUniforms = function(uniforms) {
      return uniforms.randomSeed.value = Math.random();
    };

    Materials.getTypeDefines = function() {
      var blockMaterial, blockMaterialIndex, blockTypes, blockTypesIndex, defines, ref, ref1, ref2, vegetationType, vegetationTypeIndex;
      defines = {};
      ref = ProjectGaia.BlockTypes;
      for (blockTypes in ref) {
        blockTypesIndex = ref[blockTypes];
        defines["blocks" + blockTypes] = blockTypesIndex;
      }
      ref1 = ProjectGaia.BlockMaterials;
      for (blockMaterial in ref1) {
        blockMaterialIndex = ref1[blockMaterial];
        defines["materials" + blockMaterial] = blockMaterialIndex;
      }
      ref2 = ProjectGaia.VegetationTypes;
      for (vegetationType in ref2) {
        vegetationTypeIndex = ref2[vegetationType];
        defines["vegetation" + vegetationType] = vegetationTypeIndex;
      }
      return defines;
    };

    return Materials;

  })();

}).call(this);

//# sourceMappingURL=materials.js.map
