// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  ProjectGaia.Materials = (function() {
    function Materials() {}

    Materials.getTimeUniforms = function() {
      return {
        elapsedGameTime: {
          value: 0
        },
        totalGameTime: {
          value: 0
        }
      };
    };

    Materials.updateTimeUniforms = function(uniforms, gameTime) {
      uniforms.elapsedGameTime.value = gameTime.elapsedGameTime;
      return uniforms.totalGameTime.value = gameTime.totalGameTime;
    };

    return Materials;

  })();

}).call(this);

//# sourceMappingURL=materials.js.map
