// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  ProjectGaia.Materials = (function() {
    function Materials() {}

    Materials.getTimeUniforms = function() {
      return {
        elapsedGameTime: {
          value: 0
        },
        totalGameTime: {
          value: 0
        }
      };
    };

    Materials.updateTimeUniforms = function(uniforms, gameTime) {
      uniforms.elapsedGameTime.value = gameTime.elapsedGameTime;
      return uniforms.totalGameTime.value = gameTime.totalGameTime;
    };

    Materials.getTypeDefines = function() {
      var blockMaterial, blockMaterialIndex, defines, ref, ref1, vegetationType, vegetationTypeIndex;
      defines = {};
      ref = ProjectGaia.BlockMaterials;
      for (blockMaterial in ref) {
        blockMaterialIndex = ref[blockMaterial];
        defines["materials" + (_.upperFirst(blockMaterial))] = blockMaterialIndex;
      }
      ref1 = ProjectGaia.VegetationTypes;
      for (vegetationType in ref1) {
        vegetationTypeIndex = ref1[vegetationType];
        defines["vegetation" + (_.upperFirst(vegetationType))] = vegetationTypeIndex;
      }
      return defines;
    };

    return Materials;

  })();

}).call(this);

//# sourceMappingURL=materials.js.map
