// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  ProjectGaia.BlockTypes = {
    Air: 0,
    Earth: 1,
    Water: 2
  };

  ProjectGaia.BlockMaterials = {
    Empty: 0,
    Rock: 1,
    FrozenRock: 2,
    Soil: 3,
    Snow: 4,
    Gravel: 5,
    Sand: 6,
    Mud: 7,
    Ice: 8,
    Water: 9,
    Swamp: 10,
    Steam: 11,
    Unknown1: 12,
    Unknown2: 13,
    Unknown3: 14
  };

  ProjectGaia.BlockMaterialMapping = (function() {
    function BlockMaterialMapping(mapping) {
      this.mapping = mapping;
    }

    BlockMaterialMapping.prototype.getBlockMaterialForProperties = function(propertiesOrTemperature, humidity) {
      var temperature;
      if (_.isObject(propertiesOrTemperature)) {
        temperature = propertiesOrTemperature.temperature;
        humidity = propertiesOrTemperature.humidty;
      } else {
        temperature = propertiesOrTemperature;
      }
      return this.mapping[humidity][temperature];
    };

    return BlockMaterialMapping;

  })();

}).call(this);

//# sourceMappingURL=blocktypes.js.map
