// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var blockMaterialIndex, blockMaterialName;

  ProjectGaia.BlockTypes = {
    Air: 0,
    Earth: 1,
    Water: 2,
    Vegetation: 3,
    Custom: 4
  };

  ProjectGaia.BlockMaterials = {
    Empty: 0,
    Rain: null,
    Cloud: null,
    Rock: null,
    FrozenRock: null,
    Soil: null,
    Snow: null,
    Gravel: null,
    Sand: null,
    Mud: null,
    Ice: null,
    Water: null,
    Swamp: null,
    Steam: null
  };

  blockMaterialIndex = 1;

  for (blockMaterialName in ProjectGaia.BlockMaterials) {
    if (!(ProjectGaia.BlockMaterials[blockMaterialName] == null)) {
      continue;
    }
    ProjectGaia.BlockMaterials[blockMaterialName] = blockMaterialIndex;
    blockMaterialIndex++;
  }

  ProjectGaia.BlockMaterialMapping = (function() {
    function BlockMaterialMapping(mapping) {
      this.mapping = mapping;
    }

    BlockMaterialMapping.prototype.getBlockMaterialForProperties = function(propertiesOrTemperature, humidity) {
      var temperature;
      if (_.isObject(propertiesOrTemperature)) {
        temperature = propertiesOrTemperature.temperature;
        humidity = propertiesOrTemperature.humidity;
      } else {
        temperature = propertiesOrTemperature;
      }
      return this.mapping[humidity][temperature];
    };

    return BlockMaterialMapping;

  })();

}).call(this);

//# sourceMappingURL=blocktypes.js.map
