// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  ProjectGaia.Sides = (function() {
    function Sides() {}

    Sides.Right = 0;

    Sides.Left = 1;

    Sides.Up = 2;

    Sides.Down = 3;

    Sides.Back = 4;

    Sides.Forward = 5;

    Sides.Normals = [new THREE.Vector3(1, 0, 0), new THREE.Vector3(-1, 0, 0), new THREE.Vector3(0, 1, 0), new THREE.Vector3(0, -1, 0), new THREE.Vector3(0, 0, 1), new THREE.Vector3(0, 0, -1)];

    return Sides;

  })();

}).call(this);

//# sourceMappingURL=dimensions.js.map
