// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var ProjectGaia;

  ProjectGaia = (function() {
    function ProjectGaia() {
      var createSkyColors, hexValue, shadowCameraHalfSize;
      this.renderer = new THREE.WebGLRenderer;
      this.renderer.setSize(window.innerWidth, window.innerHeight);
      this.renderer.autoClear = false;
      this.renderer.shadowMap.enabled = true;
      this.renderer.shadowMap.autoUpdate = false;
      this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;
      this.renderer.setClearColor(new THREE.Color(0.05, 0.05, 0.1), 1);
      document.body.appendChild(this.renderer.domElement);
      this.scene = new THREE.Scene;
      this.sky = new THREE.HemisphereLight;
      this.scene.add(this.sky);
      createSkyColors = (function(_this) {
        return function(hexValues) {
          var hexValue, hsl, i, len, results;
          results = [];
          for (i = 0, len = hexValues.length; i < len; i++) {
            hexValue = hexValues[i];
            hsl = new THREE.Color(hexValue).getHSL();
            results.push(new THREE.Color().setHSL(hsl.h, hsl.s * 1.2, hsl.l * 1.2));
          }
          return results;
        };
      })(this);
      this.skyColors = {
        top: createSkyColors([0x101b31, 0x101b31, 0x192c4c, 0x285e9a, 0x4471b2, 0x375696, 0x6f7d9a, 0x474b61, 0x101b31]),
        bottom: createSkyColors([0x213867, 0x213867, 0xb99b84, 0xb9bdc3, 0xb5d7f3, 0xc3dcf8, 0xf1dcb3, 0xaa6748, 0x213867])
      };
      this.sun = new THREE.DirectionalLight(0, 1);
      this.sun.castShadow = true;
      shadowCameraHalfSize = 80;
      this.sun.shadow.camera.left = -shadowCameraHalfSize;
      this.sun.shadow.camera.right = shadowCameraHalfSize;
      this.sun.shadow.camera.top = shadowCameraHalfSize;
      this.sun.shadow.camera.bottom = -shadowCameraHalfSize;
      this.sun.shadow.camera.near = 10;
      this.sun.shadow.camera.far = 200;
      this.sun.shadow.mapSize.width = 4096;
      this.sun.shadow.mapSize.height = 4096;
      this.sun.shadow.bias = -0.001;
      this.scene.add(this.sun);
      this.sunColors = (function() {
        var i, len, ref, results;
        ref = [0, 0, 0xaf855e, 0xffffca, 0xffffca, 0xffffca, 0xeec137, 0xd86726, 0];
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          hexValue = ref[i];
          results.push(new THREE.Color(hexValue));
        }
        return results;
      })();
      this.loadingManager = new THREE.LoadingManager((function(_this) {
        return function() {
          console.log("Loading finished!");
          return _this.initialize();
        };
      })(this), (function(_this) {
        return function(url, itemsLoaded, itemsTotal) {
          return console.log("Loaded " + itemsLoaded + " of " + itemsTotal);
        };
      })(this), (function(_this) {
        return function(url) {
          return console.log("Loading error with", url);
        };
      })(this));
      ProjectGaia.Materials.VoxelWorld.load(this.loadingManager);
      ProjectGaia.Materials.BlocksInformation.load(this.loadingManager);
      ProjectGaia.Materials.VegetationInformation.load(this.loadingManager);
      ProjectGaia.VoxelWorld.load(this.loadingManager);
    }

    ProjectGaia.prototype.initialize = function() {
      var ground, groundGeometry, groundMaterial, model, worldSizeVector;
      model = ProjectGaia.VoxelWorld.environmentModel;
      this.worldSize = {
        width: model.width,
        height: model.height + 20,
        depth: model.depth
      };
      worldSizeVector = new THREE.Vector3(this.worldSize.width, this.worldSize.height, this.worldSize.depth);
      groundGeometry = new THREE.PlaneBufferGeometry(this.worldSize.width + 100, this.worldSize.depth + 100);
      groundMaterial = new THREE.MeshLambertMaterial({
        color: 0x808080
      });
      ground = new THREE.Mesh(groundGeometry, groundMaterial);
      ground.receiveShadow = true;
      ground.rotation.x = -Math.PI / 2;
      this.voxelWorld = new ProjectGaia.VoxelWorld(this.worldSize);
      this.materialsDataTexture = new ProjectGaia.MaterialsDataTexture;
      this.vegetationDataTexture = new ProjectGaia.VegetationDataTexture;
      this.blocksInformationTexture = new ProjectGaia.ComputedTexture({
        renderer: this.renderer,
        initializationTexture: this.voxelWorld.startingBlocksInformationTexture,
        mapName: 'blocksInformation'
      });
      this.vegetationInformationTexture = new ProjectGaia.ComputedTexture({
        renderer: this.renderer,
        mapName: 'vegetationInformation',
        width: this.voxelWorld.startingBlocksInformationTexture.image.width,
        height: this.voxelWorld.startingBlocksInformationTexture.image.height
      });
      this.blocksInformationMaterial = new ProjectGaia.Materials.BlocksInformation({
        materialsDataTexture: this.materialsDataTexture,
        blocksInformationTexture: this.blocksInformationTexture,
        vegetationInformationTexture: this.vegetationInformationTexture,
        worldSizeVector: worldSizeVector
      });
      this.blocksInformationTexture.setMaterial(this.blocksInformationMaterial);
      this.vegetationInformationMaterial = new ProjectGaia.Materials.VegetationInformation({
        materialsDataTexture: this.materialsDataTexture,
        vegetationDataTexture: this.vegetationDataTexture,
        blocksInformationTexture: this.blocksInformationTexture,
        vegetationInformationTexture: this.vegetationInformationTexture,
        worldSizeVector: worldSizeVector
      });
      this.vegetationInformationTexture.setMaterial(this.vegetationInformationMaterial);
      this.voxelWorldMaterial = new ProjectGaia.Materials.VoxelWorld({
        materialsDataTexture: this.materialsDataTexture,
        blocksInformationTexture: this.blocksInformationTexture,
        worldSizeVector: worldSizeVector
      });
      this.voxelWorldDepthMaterial = new ProjectGaia.Materials.VoxelWorld.Depth({
        blocksInformationTexture: this.blocksInformationTexture,
        worldSizeVector: worldSizeVector
      });
      this.voxelMesh = new ProjectGaia.VoxelMesh(_.extend({
        world: this.voxelWorld,
        material: this.voxelWorldMaterial
      }, this.worldSize));
      this.voxelMesh.castShadow = true;
      this.voxelMesh.receiveShadow = true;
      this.voxelMesh.customDepthMaterial = this.voxelWorldDepthMaterial;
      this.voxelMesh.position.set(-this.worldSize.width / 2, -5, -this.worldSize.depth / 2);
      this.scene.add(this.voxelMesh);
      this.camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 1, 400);
      this.camera.position.set(0, this.worldSize.height, this.worldSize.depth * 1.75);
      this.controls = new THREE.OrbitControls(this.camera, this.renderer.domElement);
      document.addEventListener('keypress', (function(_this) {
        return function(event) {
          switch (event.keyCode) {
            case 104:
              return _this.voxelWorldMaterial.uniforms.visualizeHumidity.value = !_this.voxelWorldMaterial.uniforms.visualizeHumidity.value;
            case 116:
              return _this.voxelWorldMaterial.uniforms.visualizeTemperature.value = !_this.voxelWorldMaterial.uniforms.visualizeTemperature.value;
          }
        };
      })(this));
      this.simulationAccumulatedTime = 0;
      this.simulationGameTime = {
        totalGameTime: 0,
        elapsedGameTime: 0.2
      };
      this.vegetationUpdateGameTime = {
        totalGameTime: 0,
        elapsedGameTime: 0.2
      };
      this.vegetationAccumulatedTime = this.vegetationUpdateGameTime.elapsedGameTime / 2;
      return this.initialized = true;
    };

    ProjectGaia.prototype.update = function(gameTime) {
      if (!this.initialized) {
        return;
      }
      this.vegetationAccumulatedTime += gameTime.elapsedGameTime;
      if (this.vegetationAccumulatedTime > this.vegetationUpdateGameTime.elapsedGameTime) {
        this.vegetationAccumulatedTime -= this.vegetationUpdateGameTime.elapsedGameTime;
        this.vegetationUpdateGameTime.totalGameTime += this.vegetationUpdateGameTime.elapsedGameTime;
        this.vegetationInformationMaterial.update(this.vegetationUpdateGameTime);
        this.vegetationInformationTexture.update(this.vegetationUpdateGameTime);
      }
      this.simulationAccumulatedTime += gameTime.elapsedGameTime;
      if (this.simulationAccumulatedTime > this.simulationGameTime.elapsedGameTime) {
        this.simulationAccumulatedTime -= this.simulationGameTime.elapsedGameTime;
        this.simulationGameTime.totalGameTime += this.simulationGameTime.elapsedGameTime;
        this.blocksInformationMaterial.update(this.simulationGameTime);
        this.blocksInformationTexture.update(this.simulationGameTime);
      }
      this.voxelWorldMaterial.update(gameTime);
      this.voxelWorldDepthMaterial.update(gameTime);
      return this.controls.update(gameTime);
    };

    ProjectGaia.prototype.draw = function(gameTime) {
      var skyColorIndex, skyColorProgress, sunAngle, sunDistance, timeOfDay;
      if (!this.initialized) {
        return;
      }
      timeOfDay = (0.35 + gameTime.totalGameTime * 0.003) % 1;
      skyColorIndex = Math.floor(timeOfDay * 8);
      skyColorProgress = (timeOfDay * 8) % 1;
      this.sky.color.copy(this.skyColors.top[skyColorIndex]).lerp(this.skyColors.top[skyColorIndex + 1], skyColorProgress);
      this.sky.groundColor.copy(this.skyColors.bottom[skyColorIndex]).lerp(this.skyColors.bottom[skyColorIndex + 1], skyColorProgress);
      sunAngle = -Math.PI / 2 - timeOfDay * Math.PI * 2;
      sunDistance = (Math.sqrt(Math.pow(this.worldSize.width, 2), Math.pow(this.worldSize.height, 2)) + this.sun.shadow.camera.near) * 1.1;
      this.sun.position.set(Math.cos(sunAngle) * sunDistance, Math.sin(sunAngle) * sunDistance, sunDistance * 0.5);
      this.sun.color.copy(this.sunColors[skyColorIndex]).lerp(this.sunColors[skyColorIndex + 1], skyColorProgress);
      this.renderer.setRenderTarget(null);
      this.renderer.clear();
      this.voxelWorldMaterial.setWaterPass(false);
      this.renderer.shadowMap.needsUpdate = true;
      this.renderer.render(this.scene, this.camera);
      this.voxelWorldMaterial.setWaterPass(true);
      return this.renderer.render(this.scene, this.camera);
    };

    return ProjectGaia;

  })();

  window.ProjectGaia = ProjectGaia;

}).call(this);

//# sourceMappingURL=projectgaia.js.map
