// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  ProjectGaia.VegetationTypes = {
    Empty: 0,
    Cactus: 1,
    PineTree: 2,
    PalmTree: 3,
    BirchTree: 4
  };

}).call(this);

//# sourceMappingURL=vegetationtypes.js.map
