// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  ProjectGaia.VoxelWorld = (function() {
    function VoxelWorld(options) {
      this.options = options;
    }

    VoxelWorld.prototype.getBlockIndexForCoordinates = function(x, y, z) {
      return x + y * this.options.width + z * this.options.width * this.options.height;
    };

    return VoxelWorld;

  })();

}).call(this);

//# sourceMappingURL=voxelworld.js.map
